// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BookService 书籍服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseDir() {
    return $Call.ByID(2269118919);
}

/**
 * GetReadingProgress: 获取阅读进度（对外 API）
 * 
 * 工作流程：
 * 1. 根据文件路径计算 SHA1 哈希
 * 2. 调用 progressStore.GetProgress 查询
 * 
 * 参数：
 *   - bookPath: PDF 文件的完整路径
 * 
 * 返回：
 *   - int: 保存的页码（未找到或出错时返回 1）
 * 
 * 注意：
 * - 出错时返回默认值 1，不影响正常阅读
 * - 前端无需处理错误，直接使用返回值即可
 * @param {string} bookPath
 * @returns {$CancellablePromise<number>}
 */
export function GetReadingProgress(bookPath) {
    return $Call.ByID(2594672894, bookPath);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetScanDir() {
    return $Call.ByID(4089941077);
}

/**
 * LoadPDF: 读取文件内容返回给前端
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function LoadPDF(path) {
    return $Call.ByID(245060001, path).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * OpenInExplorer: 在资源管理器中打开文件所在目录
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(path) {
    return $Call.ByID(1860070597, path);
}

/**
 * SaveReadingProgress: 保存阅读进度（对外 API）
 * 
 * 工作流程：
 * 1. 根据文件路径计算 SHA1 哈希
 * 2. 调用 progressStore.SaveProgress 保存
 * 
 * 参数：
 *   - bookPath: PDF 文件的完整路径
 *   - page: 当前页码
 * 
 * 返回：
 *   - error: 计算哈希或保存失败时的错误
 * @param {string} bookPath
 * @param {number} page
 * @returns {$CancellablePromise<void>}
 */
export function SaveReadingProgress(bookPath, page) {
    return $Call.ByID(267789959, bookPath, page);
}

/**
 * ScanBooks: 扫描文件夹
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.BookInfo[]>}
 */
export function ScanBooks(dirPath) {
    return $Call.ByID(1419679738, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BookInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
