// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 聊天服务
 * 字段说明：
 * - mu: 互斥锁保护所有字段的并发访问
 * - config: 应用配置（缓存的单例）
 * - client: LLM API客户端（通过API_KEY初始化）
 * - conversation: 全局会话对象（仅用于非作用域的消息发送）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSession 创建新的会话
 * title为空时默认使用"新会话"作为名称
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} title
 * @returns {$CancellablePromise<$models.ChatSessionSummary>}
 */
export function CreateSession(scopeType, bookPath, title) {
    return $Call.ByID(2349580989, scopeType, bookPath, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteSession 删除指定会话
 * 删除会话文件和索引中的记录
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(scopeType, bookPath, sessionID) {
    return $Call.ByID(3245855500, scopeType, bookPath, sessionID);
}

/**
 * GetAPIKey 从缓存配置中读取API密钥
 * 无需重新加载文件，使用单例缓存
 * @returns {$CancellablePromise<string>}
 */
export function GetAPIKey() {
    return $Call.ByID(1742204374);
}

/**
 * GetTraceState 获取全局会话的当前思路摘要（trace state）
 * Trace是LLM长期记忆的核心，用于压缩冗长的对话历史
 * @returns {$CancellablePromise<string>}
 */
export function GetTraceState() {
    return $Call.ByID(3252594267);
}

/**
 * ListSessions 列出指定作用域内的所有会话
 * 返回的会话列表按UpdatedAt时间倒序排列（最新优先）
 * @param {string} scopeType
 * @param {string} bookPath
 * @returns {$CancellablePromise<$models.ChatSessionSummary[]>}
 */
export function ListSessions(scopeType, bookPath) {
    return $Call.ByID(2959228114, scopeType, bookPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * LoadSession 加载会话详情（包括完整消息历史和LLM状态）
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ChatSessionDetail>}
 */
export function LoadSession(scopeType, bookPath, sessionID) {
    return $Call.ByID(3021999501, scopeType, bookPath, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ResetConversation 重置全局会话对象
 * @returns {$CancellablePromise<void>}
 */
export function ResetConversation() {
    return $Call.ByID(1665464817);
}

/**
 * SaveAPIKey 保存新的API密钥到配置文件
 * 流程：
 *  1. 验证新API_KEY是否有效（创建临时client测试）
 *  2. 保存到配置文件
 *  3. 替换当前client对象
 *  4. 重置conversation（会在下次ensureConversationLocked时重建）
 * 
 * 如果API_KEY无效，保存失败且不会修改现有client
 * @param {string} apiKey
 * @returns {$CancellablePromise<void>}
 */
export function SaveAPIKey(apiKey) {
    return $Call.ByID(2890408737, apiKey);
}

/**
 * SendMessage 全局会话API：同步发送消息（不涉及存储）
 * 用途：快速测试、对话框交互场景不需要持久化的情形
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function SendMessage(message) {
    return $Call.ByID(1063940756, message);
}

/**
 * SendMessageInSession 在指定会话中同步发送消息（阻塞直到LLM回复）
 * 参数：
 *   - scopeType: "library" 或 "book"
 *   - bookPath: 书籍路径（scopeType=="book"时必需）
 *   - sessionID: 会话ID
 *   - message: 文本消息
 *   - imagePaths: 附加的图片路径列表（可为nil）
 * 
 * 流程：
 *  1. 从文件加载会话状态
 *  2. 恢复TracedConversation对象
 *  3. 添加图片和文本到消息缓冲
 *  4. 调用LLM API（阻塞120秒）
 *  5. 序列化新状态到文件（原子操作）
 *  6. 更新索引（最新会话优先）
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} sessionID
 * @param {string} message
 * @param {string[]} imagePaths
 * @returns {$CancellablePromise<string>}
 */
export function SendMessageInSession(scopeType, bookPath, sessionID, message, imagePaths) {
    return $Call.ByID(887274261, scopeType, bookPath, sessionID, message, imagePaths);
}

/**
 * SendMessageStream 全局会话API：异步流式发送消息
 * 与SendMessageStreamInSession的区别：不涉及存储，仅在内存中维护全局会话对象
 * 事件：
 *   - "chat_chunk" (string): 流式回复的每个文本块
 *   - "chat_done" (string): 完整回复
 *   - "chat_stream_error" (string): 发生错误
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageStream(message) {
    return $Call.ByID(1533322604, message);
}

/**
 * SendMessageStreamInSession 在指定会话中异步流式发送消息
 * 与SendMessageInSession的区别：
 *   - 返回立即（在后台goroutine中执行）
 *   - 通过Wails事件通知前端进度
 * 
 * 事件：
 *   - "chat_chunk" (string): 流式回复的每个文本块
 *   - "chat_done" (string): 完整回复（所有块拼接）
 *   - "chat_stream_error" (string): 发生错误
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} sessionID
 * @param {string} message
 * @param {string[]} imagePaths
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageStreamInSession(scopeType, bookPath, sessionID, message, imagePaths) {
    return $Call.ByID(1803555469, scopeType, bookPath, sessionID, message, imagePaths);
}

// Private type creation functions
const $$createType0 = $models.ChatSessionSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ChatSessionDetail.createFrom;
