// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadPDF: 读取文件内容返回给前端
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function LoadPDF(path) {
    return $Call.ByID(334468878, path).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * OpenInExplorer: 在资源管理器中打开文件所在目录
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(path) {
    return $Call.ByID(938676052, path);
}

/**
 * ScanBooks: 扫描文件夹
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.BookInfo[]>}
 */
export function ScanBooks(dirPath) {
    return $Call.ByID(3885217129, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BookInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
