// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BookService from "./bookservice.js";
import * as GreetService from "./greetservice.js";
export {
    BookService,
    GreetService
};

export {
    BookInfo
} from "./models.js";
