// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 聊天服务
 * 
 * 字段说明：
 *   - mu:           互斥锁，保护所有字段的并发访问
 *   - config:       应用配置（从 services/config 包获取的单例缓存）
 *   - client:       LLM API 客户端（通过 API_KEY 初始化，用于创建对话）
 *   - conversation: 全局会话对象（仅用于非作用域的旧版消息发送，不持久化）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSession 创建新的会话
 * 
 * 参数：
 *   - scopeType: 作用域类型（"library" 或 "book"）
 *   - bookPath:  书籍路径（scopeType=="book" 时必需）
 *   - title:     会话标题（为空时默认使用"新会话"）
 * 
 * 流程：
 *  1. 解析作用域并创建目录
 *  2. 生成唯一的会话 ID（基于纳秒时间戳）
 *  3. 创建空的会话文件（包含元数据但无消息）
 *  4. 更新索引文件（sessions_index.json）
 * 
 * 返回：
 *   - 新创建的会话摘要
 *   - 错误信息（如果文件写入失败）
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} title
 * @returns {$CancellablePromise<$models.ChatSessionSummary>}
 */
export function CreateSession(scopeType, bookPath, title) {
    return $Call.ByID(5555461, scopeType, bookPath, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteSession 删除指定会话
 * 
 * 参数：
 *   - scopeType: 作用域类型
 *   - bookPath:  书籍路径
 *   - sessionID: 要删除的会话 ID
 * 
 * 流程：
 *  1. 删除会话文件（s_xxx.json）
 *  2. 从索引中移除该会话的记录
 *  3. 保存更新后的索引
 * 
 * 注意：如果会话文件不存在，不会报错（静默成功）
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(scopeType, bookPath, sessionID) {
    return $Call.ByID(3838364260, scopeType, bookPath, sessionID);
}

/**
 * GetAPIKey 从缓存配置中读取 API 密钥
 * 
 * 无需重新加载文件，直接使用内存中的单例缓存。
 * 如果配置未初始化，返回空字符串。
 * 
 * 返回：
 *   - 当前配置的 API_KEY
 * @returns {$CancellablePromise<string>}
 */
export function GetAPIKey() {
    return $Call.ByID(681475326);
}

/**
 * GetModelConfig 获取模型配置（提供商和具体模型）
 * 
 * 返回：
 *   - map[string]string{"provider": 提供商, "model": 模型名称}
 *   - 如果配置未初始化，返回默认值（aliyun, qwen3-omni-flash）
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetModelConfig() {
    return $Call.ByID(4020594580).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetTraceState 获取全局会话的当前思路摘要（trace state）
 * 
 * Trace 是 LLM 长期记忆的核心，用于压缩冗长的对话历史。
 * 当对话轮数超过 maxHistory 时，LLM 会自动生成一个思路摘要，
 * 保留关键上下文信息，避免 token 超限。
 * 
 * 返回：
 *   - 当前的 trace 摘要文本（如果会话不存在，返回空字符串）
 * @returns {$CancellablePromise<string>}
 */
export function GetTraceState() {
    return $Call.ByID(193236531);
}

/**
 * ListSessions 列出指定作用域内的所有会话
 * 
 * 参数：
 *   - scopeType: 作用域类型（"library" 或 "book"）
 *   - bookPath:  书籍路径（scopeType=="book" 时必需）
 * 
 * 返回：
 *   - 按 UpdatedAt 时间倒序排列的会话列表（最新优先）
 *   - 错误信息（如果作用域解析失败）
 * @param {string} scopeType
 * @param {string} bookPath
 * @returns {$CancellablePromise<$models.ChatSessionSummary[]>}
 */
export function ListSessions(scopeType, bookPath) {
    return $Call.ByID(4236221610, scopeType, bookPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * LoadSession 加载会话详情（包括完整消息历史和 LLM 状态）
 * 
 * 参数：
 *   - scopeType: 作用域类型
 *   - bookPath:  书籍路径
 *   - sessionID: 会话 ID
 * 
 * 返回：
 *   - 完整的会话详情（包含 Summary、Messages、LLMState）
 *   - 错误信息（如果会话不存在或读取失败）
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ChatSessionDetail>}
 */
export function LoadSession(scopeType, bookPath, sessionID) {
    return $Call.ByID(3040301557, scopeType, bookPath, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ResetConversation 重置全局会话对象
 * 
 * 清空内存中的 conversation，下次调用 SendMessage 时会创建新的会话。
 * 不影响基于作用域的会话（那些会话存储在磁盘中）。
 * @returns {$CancellablePromise<void>}
 */
export function ResetConversation() {
    return $Call.ByID(809466489);
}

/**
 * SaveAPIKey 保存新的 API 密钥到配置文件
 * 
 * 流程：
 *  1. 验证新 API_KEY 是否有效（创建临时 client 测试连接）
 *  2. 保存到配置文件（同时更新内存缓存）
 *  3. 替换当前 client 对象
 *  4. 重置 conversation（会在下次 ensureConversationLocked 时重建）
 * 
 * 参数：
 *   - apiKey: 新的 API 密钥
 * 
 * 返回：
 *   - 错误信息（如果 API_KEY 无效或文件写入失败）
 * 
 * 注意：
 *   - 如果 API_KEY 无效，保存失败且不会修改现有 client
 *   - 保存成功后，后续对话会自动使用新的 API_KEY
 * @param {string} apiKey
 * @returns {$CancellablePromise<void>}
 */
export function SaveAPIKey(apiKey) {
    return $Call.ByID(3119252441, apiKey);
}

/**
 * SaveModelConfig 保存模型配置到配置文件
 * 
 * 参数：
 *   - config: map[string]string{"provider": 提供商, "model": 模型名称}
 * 
 * 流程：
 *  1. 更新内存中的配置
 *  2. 保存到文件
 *  3. 如果 client 已初始化，重新创建以使用新配置
 *  4. 重置 conversation（下次对话时重建）
 * 
 * 返回：
 *   - 错误信息（如果文件写入失败）
 * 
 * 注意：
 *   - 更换模型后，现有会话的 LLMState 仍然有效
 *   - 新消息会使用新的模型生成回复
 * @param {{ [_ in string]?: string }} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveModelConfig(config) {
    return $Call.ByID(3853342737, config);
}

/**
 * SendMessage 全局会话 API：同步发送消息（不涉及存储）
 * 
 * 用途：
 *   - 快速测试 LLM 连接
 *   - 对话框交互场景不需要持久化的情形
 *   - 遗留接口，推荐使用基于作用域的 SendMessageInSession
 * 
 * 参数：
 *   - message: 文本消息
 * 
 * 返回：
 *   - LLM 的完整回复
 *   - 错误信息（如果 client 未初始化或 API 调用失败）
 * 
 * 注意：
 *   - 此方法不保存任何数据到磁盘
 *   - 会话状态仅保存在内存中，重启后丢失
 * @param {string} message
 * @returns {$CancellablePromise<string>}
 */
export function SendMessage(message) {
    return $Call.ByID(2484497676, message);
}

/**
 * SendMessageInSession 在指定会话中同步发送消息（阻塞直到 LLM 回复）
 * 
 * 参数：
 *   - scopeType:  "library" 或 "book"
 *   - bookPath:   书籍路径（scopeType=="book" 时必需）
 *   - sessionID:  会话 ID
 *   - message:    文本消息内容
 *   - imagePaths: 附加的图片路径列表（可为 nil）
 * 
 * 流程：
 *  1. 从文件加载会话状态（包括 LLMStateJSON 和 Messages）
 *  2. 恢复 TracedConversation 对象（从 LLMStateJSON 反序列化）
 *  3. 添加图片和文本到消息缓冲
 *  4. 调用 LLM API（阻塞最多 120 秒）
 *  5. 序列化新状态到文件（原子操作：临时文件 + rename）
 *  6. 更新索引（将该会话移到列表顶部）
 * 
 * 返回：
 *   - LLM 的完整回复文本
 *   - 错误信息（如果 API 调用失败或文件写入失败）
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} sessionID
 * @param {string} message
 * @param {string[]} imagePaths
 * @returns {$CancellablePromise<string>}
 */
export function SendMessageInSession(scopeType, bookPath, sessionID, message, imagePaths) {
    return $Call.ByID(978241453, scopeType, bookPath, sessionID, message, imagePaths);
}

/**
 * SendMessageStream 全局会话 API：异步流式发送消息
 * 
 * 与 SendMessageStreamInSession 的区别：
 *   - 不涉及存储，仅在内存中维护全局会话对象
 *   - 重启后会话丢失
 *   - 遗留接口，推荐使用基于作用域的 SendMessageStreamInSession
 * 
 * 参数：
 *   - message: 文本消息
 * 
 * 触发的事件：
 *   - "chat_chunk"        (string): 流式回复的每个文本块
 *   - "chat_done"         (string): 完整回复
 *   - "chat_stream_error" (string): 发生错误
 * 
 * 注意：
 *   - 立即返回，实际发送在后台 goroutine 中执行
 *   - 即使返回 nil，也可能通过 chat_stream_error 事件报告错误
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageStream(message) {
    return $Call.ByID(3338547028, message);
}

/**
 * SendMessageStreamInSession 在指定会话中异步流式发送消息
 * 
 * 与 SendMessageInSession 的区别：
 *   - 立即返回（在后台 goroutine 中执行，不阻塞调用者）
 *   - 通过 Wails 事件通知前端进度（实时显示回复）
 * 
 * 参数：
 *   - scopeType:  作用域类型
 *   - bookPath:   书籍路径
 *   - sessionID:  会话 ID
 *   - message:    文本消息
 *   - imagePaths: 图片路径列表
 * 
 * 触发的事件：
 *   - "chat_chunk"        (string): 流式回复的每个文本块（实时推送）
 *   - "chat_done"         (string): 完整回复（所有块拼接后的最终结果）
 *   - "chat_stream_error" (string): 发生错误时的错误信息
 * 
 * 注意：
 *   - 即使返回 nil，实际的消息发送可能在后台失败（通过 chat_stream_error 事件通知）
 *   - 保存用户消息时会记录附件（imagePaths）
 * @param {string} scopeType
 * @param {string} bookPath
 * @param {string} sessionID
 * @param {string} message
 * @param {string[]} imagePaths
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageStreamInSession(scopeType, bookPath, sessionID, message, imagePaths) {
    return $Call.ByID(192468181, scopeType, bookPath, sessionID, message, imagePaths);
}

// Private type creation functions
const $$createType0 = $models.ChatSessionSummary.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.ChatSessionDetail.createFrom;
