// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChatMessageRecord 存储在会话中的单条消息记录
 * 
 * 用途：
 *   - 向前端返回完整对话历史供 UI 渲染
 *   - 独立于 LLM 状态存储（应用层维护的消息列表）
 */
export class ChatMessageRecord {
    /**
     * Creates a new ChatMessageRecord instance.
     * @param {Partial<ChatMessageRecord>} [$$source = {}] - The source object to create the ChatMessageRecord.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * "user" 或 "assistant"
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * 消息内容（文本）
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 附件列表（图片路径或 base64）
             * @member
             * @type {string[] | undefined}
             */
            this["attachments"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * RFC3339 时间戳
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessageRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatMessageRecord}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField2_0($$parsedSource["attachments"]);
        }
        return new ChatMessageRecord(/** @type {Partial<ChatMessageRecord>} */($$parsedSource));
    }
}

/**
 * ChatSessionDetail 完整会话详情（前端查看会话时返回）
 * 
 * 包含三部分：
 *   - Summary:  会话元数据（标题、时间等）
 *   - Messages: UI 显示的消息列表
 *   - LLMState: TracedConversation.ExportJSON() 序列化后的状态
 */
export class ChatSessionDetail {
    /**
     * Creates a new ChatSessionDetail instance.
     * @param {Partial<ChatSessionDetail>} [$$source = {}] - The source object to create the ChatSessionDetail.
     */
    constructor($$source = {}) {
        if (!("summary" in $$source)) {
            /**
             * 会话元数据
             * @member
             * @type {ChatSessionSummary}
             */
            this["summary"] = (new ChatSessionSummary());
        }
        if (!("messages" in $$source)) {
            /**
             * UI 显示的消息列表
             * @member
             * @type {ChatMessageRecord[]}
             */
            this["messages"] = [];
        }
        if (!("llm_state_json" in $$source)) {
            /**
             * TracedConversation 状态
             * @member
             * @type {string}
             */
            this["llm_state_json"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSessionDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatSessionDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField0_0($$parsedSource["summary"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField1_0($$parsedSource["messages"]);
        }
        return new ChatSessionDetail(/** @type {Partial<ChatSessionDetail>} */($$parsedSource));
    }
}

/**
 * ChatSessionSummary 会话摘要，用于列表显示（不包含完整消息历史）
 * 
 * 用途：
 *   - 快速展示所有会话列表，避免加载完整的消息历史
 *   - 在 UI 中显示会话卡片（标题、时间、预览）
 */
export class ChatSessionSummary {
    /**
     * Creates a new ChatSessionSummary instance.
     * @param {Partial<ChatSessionSummary>} [$$source = {}] - The source object to create the ChatSessionSummary.
     */
    constructor($$source = {}) {
        if (!("session_id" in $$source)) {
            /**
             * 唯一标识，格式: s_<nanoseconds>
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("scope_type" in $$source)) {
            /**
             * "library" 或 "book"
             * @member
             * @type {string}
             */
            this["scope_type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 书籍内容 SHA1（仅 book 作用域）
             * @member
             * @type {string | undefined}
             */
            this["book_hash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 书籍文件路径（仅 book 作用域）
             * @member
             * @type {string | undefined}
             */
            this["book_path"] = undefined;
        }
        if (!("title" in $$source)) {
            /**
             * 用户设置的会话名称
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * RFC3339 时间戳
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            /**
             * 最后更新时间（用于排序）
             * @member
             * @type {string}
             */
            this["updated_at"] = "";
        }
        if (!("message_count" in $$source)) {
            /**
             * 消息总数
             * @member
             * @type {number}
             */
            this["message_count"] = 0;
        }
        if (!("last_message_preview" in $$source)) {
            /**
             * 最后一条消息的前 80 字符预览
             * @member
             * @type {string}
             */
            this["last_message_preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSessionSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatSessionSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSessionSummary(/** @type {Partial<ChatSessionSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ChatSessionSummary.createFrom;
const $$createType2 = ChatMessageRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
